[project]
name = "mentralaunchhack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dataset>=1.6.2",
    "fastapi>=0.104.1",
    "uvicorn[standard]>=0.24.0",
]
